-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2240','NEGARA','3' FROM dual
 UNION ALL

	  SELECT '2563','SELA','4' FROM dual
 UNION ALL

	  SELECT '1649','SUNGAI PINANG','3' FROM dual
 UNION ALL

	  SELECT '0365','PURWOREJO','3' FROM dual
 UNION ALL

	  SELECT '0366','SEMARANG','2' FROM dual
 UNION ALL

	  SELECT '2564','SUPIORI','3' FROM dual
 UNION ALL

	  SELECT '2464','MALAKA','3' FROM dual
 UNION ALL

	  SELECT '2341','UTAN','3' FROM dual
 UNION ALL

	  SELECT '1967','UJUNG PANDANG','2' FROM dual
 UNION ALL

	  SELECT '2344','PRAYA','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0753','BINJAI','2' FROM dual
 UNION ALL

	  SELECT '2541','BIAK','3' FROM dual
 UNION ALL

	  SELECT '0402','YOGYAKARTA','2' FROM dual
 UNION ALL

	  SELECT '0367','KABUPATEN KUDUS','2' FROM dual
 UNION ALL

	  SELECT '1552','BANJARBARU','2' FROM dual
 UNION ALL

	  SELECT '0368','SURAKARTA','2' FROM dual
 UNION ALL

	  SELECT '2465','KAB. MALAKA','2' FROM dual
 UNION ALL

	  SELECT '0369','WONOSOBO','2' FROM dual
 UNION ALL

	  SELECT '1966','LIMBUNG','3' FROM dual
 UNION ALL

	  SELECT '2342','SUMBAWA BESAR','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0371','PURBALINGGA','2' FROM dual
 UNION ALL

	  SELECT '1652','TANJUNG REDEB','4' FROM dual
 UNION ALL

	  SELECT '0572','MALANG','1' FROM dual
 UNION ALL

	  SELECT '1744','TIBAWA','4' FROM dual
 UNION ALL

	  SELECT '2565','PANIAI','3' FROM dual
 UNION ALL

	  SELECT '0274','TANGERANG','2' FROM dual
 UNION ALL

	  SELECT '1303','PONTIANAK','2' FROM dual
 UNION ALL

	  SELECT '2345','DOMPU','2' FROM dual
 UNION ALL

	  SELECT '2022','KENDARI','2' FROM dual
 UNION ALL

	  SELECT '1403','PALANGKA RAYA','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2347','BIMA','3' FROM dual
 UNION ALL

	  SELECT '0380','PURWOKERTO','3' FROM dual
 UNION ALL

	  SELECT '0382','BANYUMAS','3' FROM dual
 UNION ALL

	  SELECT '1745','AIRMADIDI','3' FROM dual
 UNION ALL

	  SELECT '2459','KAB. LEMBATA',NULL FROM dual
 UNION ALL

	  SELECT '1545','KAB. KOTABARU','3' FROM dual
 UNION ALL

	  SELECT '1647','MALINAU',NULL FROM dual
 UNION ALL

	  SELECT '89','Lain-Lain','1' FROM dual
 UNION ALL

	  SELECT '8999','Lain-Lain','3' FROM dual
 UNION ALL

	  SELECT '2548','KAB. BOVEN DIGOEL','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '9420','MALAYSIA',NULL FROM dual
 UNION ALL

	  SELECT '9421','KUALA LUMPUR','2' FROM dual
 UNION ALL

	  SELECT '1139','KABUPATEN',NULL FROM dual
 UNION ALL

	  SELECT '2038','WAKATOBI','3' FROM dual
 UNION ALL

	  SELECT '2460','Ruteng','2' FROM dual
 UNION ALL

	  SELECT '2461','Ruteng','3' FROM dual
 UNION ALL

	  SELECT '9423','DOHA','3' FROM dual
 UNION ALL

	  SELECT '888','tes','3' FROM dual
 UNION ALL

	  SELECT '5555','JERMAN',NULL FROM dual
 UNION ALL

	  SELECT '28','BANTEN','1' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2801','KABUPATEN PANDEGLANG','3' FROM dual
 UNION ALL

	  SELECT '2802','KABUPATEN LEBAK','3' FROM dual
 UNION ALL

	  SELECT '2803','KABUPATEN TANGERANG','3' FROM dual
 UNION ALL

	  SELECT '2804','KABUPATEN SERANG','3' FROM dual
 UNION ALL

	  SELECT '2851','TANGERANG','3' FROM dual
 UNION ALL

	  SELECT '2852','CILEGON','2' FROM dual
 UNION ALL

	  SELECT '29','MALUKU UTARA','1' FROM dual
 UNION ALL

	  SELECT '2901','KABUPATEN MALUKU UTARA','3' FROM dual
 UNION ALL

	  SELECT '2902','KABUPATEN HALMAHERA TENGAH','3' FROM dual
 UNION ALL

	  SELECT '2903','KABUPATEN PULAU SULA','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2904','KABUPATEN HALMAHERA SELATAN','3' FROM dual
 UNION ALL

	  SELECT '2905','KABUPATEN HALMAHERA UTARA','3' FROM dual
 UNION ALL

	  SELECT '2906','KABUPATEN HALMAHERA TIMUR','3' FROM dual
 UNION ALL

	  SELECT '2951','TERNATE','2' FROM dual
 UNION ALL

	  SELECT '2952','TIDORE','2' FROM dual
 UNION ALL

	  SELECT '30','BANGKA BELITUNG','1' FROM dual
 UNION ALL

	  SELECT '3001','KABUPATEN BANGKA','3' FROM dual
 UNION ALL

	  SELECT '3002','KABUPATEN BELITUNG','3' FROM dual
 UNION ALL

	  SELECT '3003','KABUPATEN BANGKA SELATAN','3' FROM dual
 UNION ALL

	  SELECT '3004','KABUPATEN BANGKA TENGAH','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '3005','KABUPATEN BANGKA BARAT','3' FROM dual
 UNION ALL

	  SELECT '3006','KABUPATEN BELITUNG TIMUR','3' FROM dual
 UNION ALL

	  SELECT '3051','PANGKALPINANG','2' FROM dual
 UNION ALL

	  SELECT '31','GORONTALO','1' FROM dual
 UNION ALL

	  SELECT '3101','KABUPATEN BOALEMO','3' FROM dual
 UNION ALL

	  SELECT '3102','KABUPATEN GORONTALO','3' FROM dual
 UNION ALL

	  SELECT '3103','KABUPATEN PUHUWATO','3' FROM dual
 UNION ALL

	  SELECT '3104','KABUPATEN BONE BOLANGO','3' FROM dual
 UNION ALL

	  SELECT '3151','GORONTALO','2' FROM dual
 UNION ALL

	  SELECT '32','IRIAN JAYA BARAT','1' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '3201','KABUPATEN FAK-FAK','3' FROM dual
 UNION ALL

	  SELECT '3202','KABUPATEN SORONG','3' FROM dual
 UNION ALL

	  SELECT '3203','KABUPATEN MANOKWARI','3' FROM dual
 UNION ALL

	  SELECT '3204','KABUPATEN KAIMANA','3' FROM dual
 UNION ALL

	  SELECT '3205','KABUPATEN SORONG SELATAN','3' FROM dual
 UNION ALL

	  SELECT '3206','KABUPATEN RAJA AMPAT','3' FROM dual
 UNION ALL

	  SELECT '3207','KABUPATEN BINTUNI BAY','3' FROM dual
 UNION ALL

	  SELECT '3208','KABUPATEN WONDANA BAY','3' FROM dual
 UNION ALL

	  SELECT '3251','SORONG','2' FROM dual
 UNION ALL

	  SELECT '33','KEPULAUAN RIAU','1' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '3301','KABUPATEN KARIMUN','3' FROM dual
 UNION ALL

	  SELECT '3302','KABUPATEN KEPULAUAN RIAU','3' FROM dual
 UNION ALL

	  SELECT '3303','KABUPATEN NATUNA','3' FROM dual
 UNION ALL

	  SELECT '3351','BATAM','2' FROM dual
 UNION ALL

	  SELECT '3352','TANJUNG PINANG','2' FROM dual
 UNION ALL

	  SELECT '94','ASIA','1' FROM dual
 UNION ALL

	  SELECT '95','AMERIKA','1' FROM dual
 UNION ALL

	  SELECT '96','EUROPE','1' FROM dual
 UNION ALL

	  SELECT '97','AUSTRALIA',NULL FROM dual
 UNION ALL

	  SELECT '98','AFRICA','1' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '34','SULAWESI BARAT','1' FROM dual
 UNION ALL

	  SELECT '3401','KABUPATEN MAMUJU','3' FROM dual
 UNION ALL

	  SELECT '3402','KABUPATEN MAMUJU UTARA','3' FROM dual
 UNION ALL

	  SELECT '3403','KABUPATEN MAJENE','3' FROM dual
 UNION ALL

	  SELECT '3404','KABUPATEN POLEWALI','3' FROM dual
 UNION ALL

	  SELECT '3405','MAMASA','2' FROM dual
 UNION ALL

	  SELECT '1546','KUALA KURUN - GUNUNG MAS',NULL FROM dual
 UNION ALL

	  SELECT '1964','WATAMPONE','2' FROM dual
 UNION ALL

	  SELECT '9701','PERTH','2' FROM dual
 UNION ALL

	  SELECT '2222','tes','5' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2223','tes1','5' FROM dual
 UNION ALL

	  SELECT '9401','JEDDAH (ARAB SAUDI)',NULL FROM dual
 UNION ALL

	  SELECT '3000','PAPUA BARAT','1' FROM dual
 UNION ALL

	  SELECT '1038','KAB. SAROLANGUN','3' FROM dual
 UNION ALL

	  SELECT '1739','TANAH TORAJA',NULL FROM dual
 UNION ALL

	  SELECT '1235','PADANG PANJANG','3' FROM dual
 UNION ALL

	  SELECT '2457','KAB. SUMBA UTARA',NULL FROM dual
 UNION ALL

	  SELECT '2458','KAB. SUMBA SELATAN',NULL FROM dual
 UNION ALL

	  SELECT '6501','SINGAPORE','1' FROM dual
 UNION ALL

	  SELECT '2744','MANATUTO',NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1931','KAB. SELAYAR','3' FROM dual
 UNION ALL

	  SELECT '1932','KAB. BULUKOMBA','3' FROM dual
 UNION ALL

	  SELECT '1933','KAB. BANTAENG','3' FROM dual
 UNION ALL

	  SELECT '1934','KAB. JENEPONTO','3' FROM dual
 UNION ALL

	  SELECT '1935','KAB. TAKALAR','3' FROM dual
 UNION ALL

	  SELECT '1936','KAB. GOWA','3' FROM dual
 UNION ALL

	  SELECT '1937','KAB. SINJAI','3' FROM dual
 UNION ALL

	  SELECT '1938','KAB. BONE','3' FROM dual
 UNION ALL

	  SELECT '1939','KAB. MAROS','3' FROM dual
 UNION ALL

	  SELECT '1940','KAB. PANGKAJENE','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1941','KAB. BARRU','3' FROM dual
 UNION ALL

	  SELECT '1942','KAB. SOPPENG','3' FROM dual
 UNION ALL

	  SELECT '1943','KAB. WAJO','3' FROM dual
 UNION ALL

	  SELECT '1944','KAB. SINDERENG RAMPANG','3' FROM dual
 UNION ALL

	  SELECT '1945','KAB. PINRANG','3' FROM dual
 UNION ALL

	  SELECT '1946','KAB. ENREKANG','3' FROM dual
 UNION ALL

	  SELECT '1947','KAB. LUWU','3' FROM dual
 UNION ALL

	  SELECT '1948','KAB. TANA TORAJA','3' FROM dual
 UNION ALL

	  SELECT '1949','KAB. POLEWALI MEMASA','3' FROM dual
 UNION ALL

	  SELECT '1950','KAB. MAJENE','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1951','KAB. MAMUJU','3' FROM dual
 UNION ALL

	  SELECT '2021','KOTIP KENDARI','4' FROM dual
 UNION ALL

	  SELECT '2031','KAB. KENDARI','3' FROM dual
 UNION ALL

	  SELECT '2032','KAB. BUTON','3' FROM dual
 UNION ALL

	  SELECT '2033','KAB. KOLAKA','3' FROM dual
 UNION ALL

	  SELECT '2034','KAB. MUNA','3' FROM dual
 UNION ALL

	  SELECT '2101','KODYA MALUKU','2' FROM dual
 UNION ALL

	  SELECT '2121','KOTIP TERNATE','4' FROM dual
 UNION ALL

	  SELECT '2131','KAB. MALUKU TENGGARA','3' FROM dual
 UNION ALL

	  SELECT '2132','KAB. MALUKU TENGAH','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2133','KAB. HALMAHERA TENGAH','3' FROM dual
 UNION ALL

	  SELECT '2134','KAB. MALUKU UTARA','3' FROM dual
 UNION ALL

	  SELECT '2221','KOTIP DENPASAR','4' FROM dual
 UNION ALL

	  SELECT '2231','KAB. BADUNG','3' FROM dual
 UNION ALL

	  SELECT '2232','KAB. BANGLI','3' FROM dual
 UNION ALL

	  SELECT '2233','KAB. BULELENG','3' FROM dual
 UNION ALL

	  SELECT '2234','KAB. GIANYAR','3' FROM dual
 UNION ALL

	  SELECT '2235','KAB. JEMBRANA','3' FROM dual
 UNION ALL

	  SELECT '2236','KAB. KARANG ASEM','3' FROM dual
 UNION ALL

	  SELECT '2237','KAB. KLUNGKUNG','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2238','KAB. TABANAN','3' FROM dual
 UNION ALL

	  SELECT '2321','KOTIP MATARAM','4' FROM dual
 UNION ALL

	  SELECT '2331','KAB. BIMA','3' FROM dual
 UNION ALL

	  SELECT '2332','KAB. DOMPU','3' FROM dual
 UNION ALL

	  SELECT '2333','KAB. LOMBOK BARAT','3' FROM dual
 UNION ALL

	  SELECT '2334','KAB. LOMBOK TENGAH','3' FROM dual
 UNION ALL

	  SELECT '2335','KAB. LOMBOK TIMUR','3' FROM dual
 UNION ALL

	  SELECT '2336','KAB. SUMBAWA','3' FROM dual
 UNION ALL

	  SELECT '2421','KOTIP KUPANG','4' FROM dual
 UNION ALL

	  SELECT '2431','KAB. SUMBA BARAT','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2432','KAB. SUMBA TIMUR','3' FROM dual
 UNION ALL

	  SELECT '2433','KAB. TIMOR TENGAH SELATAN','3' FROM dual
 UNION ALL

	  SELECT '2434','KAB. TIMOR TENGAH BARAT','3' FROM dual
 UNION ALL

	  SELECT '2435','KAB. BELU','3' FROM dual
 UNION ALL

	  SELECT '2436','KAB. ALOR','3' FROM dual
 UNION ALL

	  SELECT '2437','KAB. FLORES TIMUR','3' FROM dual
 UNION ALL

	  SELECT '2438','KAB. SIKKA','3' FROM dual
 UNION ALL

	  SELECT '2439','KAB. ENDE','3' FROM dual
 UNION ALL

	  SELECT '2440','KAB. NGADE','3' FROM dual
 UNION ALL

	  SELECT '2441','KAB. MANGGARAI','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2521','KOTIP JAYAPURA','4' FROM dual
 UNION ALL

	  SELECT '2531','KAB. FAK FAK','3' FROM dual
 UNION ALL

	  SELECT '2532','KAB. JAYA WIJAYA','3' FROM dual
 UNION ALL

	  SELECT '2533','KAB. MANOKWARI','3' FROM dual
 UNION ALL

	  SELECT '2534','KAB. MERAUKE','3' FROM dual
 UNION ALL

	  SELECT '2535','KAB. PANIAI/NABIRE','3' FROM dual
 UNION ALL

	  SELECT '2536','KAB. SORONG','3' FROM dual
 UNION ALL

	  SELECT '2537','KAB. TELUK CENDRAWASIH','3' FROM dual
 UNION ALL

	  SELECT '2538','KAB. YAPEN WAROPEN','3' FROM dual
 UNION ALL

	  SELECT '2601','KODYA BENGKULU','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2631','KAB. BENGKULU SELATAN','3' FROM dual
 UNION ALL

	  SELECT '2632','KAB. BENGKULU UTARA','3' FROM dual
 UNION ALL

	  SELECT '2633','KAB. REJANG LEBONG','3' FROM dual
 UNION ALL

	  SELECT '2721','KOTIP DILI','4' FROM dual
 UNION ALL

	  SELECT '2731','KAB. BAUCAU','3' FROM dual
 UNION ALL

	  SELECT '2732','KAB. MANATURO','3' FROM dual
 UNION ALL

	  SELECT '2733','KAB. LAUTEM','3' FROM dual
 UNION ALL

	  SELECT '2734','KAB. VIQUEQUE','3' FROM dual
 UNION ALL

	  SELECT '2735','KAB. AINARO','3' FROM dual
 UNION ALL

	  SELECT '2736','KAB. MANIFAHI','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2737','KAB. KOVA LIMA','3' FROM dual
 UNION ALL

	  SELECT '2738','KAB. AMBENO','3' FROM dual
 UNION ALL

	  SELECT '2739','KAB. BOBONARO','3' FROM dual
 UNION ALL

	  SELECT '2740','KAB. LIQUICA','3' FROM dual
 UNION ALL

	  SELECT '2741','KAB. ERMERA','3' FROM dual
 UNION ALL

	  SELECT '2742','KAB. AILEU','3' FROM dual
 UNION ALL

	  SELECT '0000',NULL,'*' FROM dual
 UNION ALL

	  SELECT '0119','?','*' FROM dual
 UNION ALL

	  SELECT '0121','?','*' FROM dual
 UNION ALL

	  SELECT '2122','?','*' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2123','?','*' FROM dual
 UNION ALL

	  SELECT '2124','?','*' FROM dual
 UNION ALL

	  SELECT '3123','?','*' FROM dual
 UNION ALL

	  SELECT '3505','?','*' FROM dual
 UNION ALL

	  SELECT '4305','?','*' FROM dual
 UNION ALL

	  SELECT '4505','?','*' FROM dual
 UNION ALL

	  SELECT '4805','?','*' FROM dual
 UNION ALL

	  SELECT '5005','?','*' FROM dual
 UNION ALL

	  SELECT '5505','?','*' FROM dual
 UNION ALL

	  SELECT '0500','?','*' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1835','PAGIMANA','*' FROM dual
 UNION ALL

	  SELECT '5903',NULL,NULL FROM dual
 UNION ALL

	  SELECT '3424',NULL,NULL FROM dual
 UNION ALL

	  SELECT '0207',NULL,'*' FROM dual
 UNION ALL

	  SELECT '0002',NULL,'*' FROM dual
 UNION ALL

	  SELECT '0530',NULL,'*' FROM dual
 UNION ALL

	  SELECT '0133',NULL,'*' FROM dual
 UNION ALL

	  SELECT '5550',NULL,NULL FROM dual
 UNION ALL

	  SELECT '0021',NULL,'*' FROM dual
 UNION ALL

	  SELECT '5545',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0445',NULL,NULL FROM dual
 UNION ALL

	  SELECT '0146',NULL,'*' FROM dual
 UNION ALL

	  SELECT '1502',NULL,'*' FROM dual
 UNION ALL

	  SELECT '0587',NULL,'*' FROM dual
 UNION ALL

	  SELECT '5501','BANYAK KOTA',NULL FROM dual
 UNION ALL

	  SELECT '1441','SAMPIT','*' FROM dual
 UNION ALL

	  SELECT '0589',NULL,'*' FROM dual
 UNION ALL

	  SELECT '0360','KODYA CEPU','*' FROM dual
 UNION ALL

	  SELECT '0268','MERAK','*' FROM dual
 UNION ALL

	  SELECT '1635','KODYA TENGGARONG',NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2539','KAB. BIAK NUM FOR','3' FROM dual
 UNION ALL

	  SELECT '1337','PEMANGKAT','*' FROM dual
 UNION ALL

	  SELECT '2137','KODYA AMBON','2' FROM dual
 UNION ALL

	  SELECT '0361','AMBARAWA','*' FROM dual
 UNION ALL

	  SELECT '2443','KALABAHI','*' FROM dual
 UNION ALL

	  SELECT '2444','KEFAMENANU','*' FROM dual
 UNION ALL

	  SELECT '2139','TANTUI','*' FROM dual
 UNION ALL

	  SELECT '0742','SIDIKALANG','*' FROM dual
 UNION ALL

	  SELECT '1636','BUNYU','*' FROM dual
 UNION ALL

	  SELECT '2445','TIBAKISA','*' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2446','WAINGAPU','*' FROM dual
 UNION ALL

	  SELECT '2447','SOE','*' FROM dual
 UNION ALL

	  SELECT '2449','NGADA',NULL FROM dual
 UNION ALL

	  SELECT '1638','BONTANG','*' FROM dual
 UNION ALL

	  SELECT '2450','WIWIPEMO',NULL FROM dual
 UNION ALL

	  SELECT '1953','SOROAKO','*' FROM dual
 UNION ALL

	  SELECT '1734','KOTAMOBAGU','*' FROM dual
 UNION ALL

	  SELECT '2451','KAMPUNG PELITA',NULL FROM dual
 UNION ALL

	  SELECT '2452','ATAMBUA',NULL FROM dual
 UNION ALL

	  SELECT '1955','PALOPO','*' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1956','MAKASSAR','*' FROM dual
 UNION ALL

	  SELECT '2037','TOMBA','*' FROM dual
 UNION ALL

	  SELECT '2544','SERUI','*' FROM dual
 UNION ALL

	  SELECT '9999','CAIRNS (AUSTRALIA)',NULL FROM dual
 UNION ALL

	  SELECT '2251','SINGARAJA','*' FROM dual
 UNION ALL

	  SELECT '1443','PANGKALAN BUN',NULL FROM dual
 UNION ALL

	  SELECT '1641','NUNUKAN',NULL FROM dual
 UNION ALL

	  SELECT '1542','KAB. AMUNTAI','3' FROM dual
 UNION ALL

	  SELECT '1736','TAHUNA',NULL FROM dual
 UNION ALL

	  SELECT '2455','TASIFETO BARAT',NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1957','KAB. PANAIKANG',NULL FROM dual
 UNION ALL

	  SELECT '1837','TOLAI',NULL FROM dual
 UNION ALL

	  SELECT '1642','SANGATTA',NULL FROM dual
 UNION ALL

	  SELECT '0746','BELAWAN',NULL FROM dual
 UNION ALL

	  SELECT '2546','WAMENA',NULL FROM dual
 UNION ALL

	  SELECT '2547','TIMIKA',NULL FROM dual
 UNION ALL

	  SELECT '0747','SARIMATONDANG',NULL FROM dual
 UNION ALL

	  SELECT '0748','SIDAMANIK',NULL FROM dual
 UNION ALL

	  SELECT '1738','SATAL',NULL FROM dual
 UNION ALL

	  SELECT '8888','CANBERRA AUSTRALIA',NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1543','KAB. RANTAU','3' FROM dual
 UNION ALL

	  SELECT '1234','BANDAR LAMPUNG',NULL FROM dual
 UNION ALL

	  SELECT '0593','KAB. KERTOSONO',NULL FROM dual
 UNION ALL

	  SELECT '1643','PONTAK',NULL FROM dual
 UNION ALL

	  SELECT '0749','LABUHAN BATU',NULL FROM dual
 UNION ALL

	  SELECT '1958','BATAM',NULL FROM dual
 UNION ALL

	  SELECT '1644','TARAKAN','2' FROM dual
 UNION ALL

	  SELECT '0594','KOTIP. BATU','3' FROM dual
 UNION ALL

	  SELECT '2252','UBUD',NULL FROM dual
 UNION ALL

	  SELECT '2140','SANANA',NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0750','ASAHAN',NULL FROM dual
 UNION ALL

	  SELECT '1444','MUARA TEWEH',NULL FROM dual
 UNION ALL

	  SELECT '1959','SOROAKO',NULL FROM dual
 UNION ALL

	  SELECT '1960','RANTEPAO',NULL FROM dual
 UNION ALL

	  SELECT '2743','MAUMERE',NULL FROM dual
 UNION ALL

	  SELECT '1645','TANJUNG SELOR',NULL FROM dual
 UNION ALL

	  SELECT '1838','AMPANA',NULL FROM dual
 UNION ALL

	  SELECT '0269','SUMEDANG',NULL FROM dual
 UNION ALL

	  SELECT '2141','SERAM',NULL FROM dual
 UNION ALL

	  SELECT '1839','BETELEME',NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2456','LARANTUKA',NULL FROM dual
 UNION ALL

	  SELECT '1646','TANAH GROGOT',NULL FROM dual
 UNION ALL

	  SELECT '1544','BATULICIN',NULL FROM dual
 UNION ALL

	  SELECT '7777','MEKKAH',NULL FROM dual
 UNION ALL

	  SELECT '0304','KODYA SEMARANG','2' FROM dual
 UNION ALL

	  SELECT '0305','KODYA PEKALONGAN','2' FROM dual
 UNION ALL

	  SELECT '0306','KODYA TEGAL','2' FROM dual
 UNION ALL

	  SELECT '01','DKI JAKARTA','1' FROM dual
 UNION ALL

	  SELECT '02','JAWA BARAT','1' FROM dual
 UNION ALL

	  SELECT '03','JAWA TENGAH','1' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '04','DAERAH ISTIMEWA YOGYAKARTA','1' FROM dual
 UNION ALL

	  SELECT '05','JAWA TIMUR','1' FROM dual
 UNION ALL

	  SELECT '06','NANGROE ACEH DARUSSALAM','1' FROM dual
 UNION ALL

	  SELECT '07','SUMATERA UTARA','1' FROM dual
 UNION ALL

	  SELECT '08','SUMATERA BARAT','1' FROM dual
 UNION ALL

	  SELECT '09','RIAU','1' FROM dual
 UNION ALL

	  SELECT '10','JAMBI','1' FROM dual
 UNION ALL

	  SELECT '11','SUMATERA SELATAN','1' FROM dual
 UNION ALL

	  SELECT '12','LAMPUNG','1' FROM dual
 UNION ALL

	  SELECT '13','KALIMANTAN BARAT','1' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '14','KALIMANTAN TENGAH','1' FROM dual
 UNION ALL

	  SELECT '15','KALIMANTAN SELATAN','1' FROM dual
 UNION ALL

	  SELECT '16','KALIMANTAN TIMUR','1' FROM dual
 UNION ALL

	  SELECT '17','SULAWESI UTARA','1' FROM dual
 UNION ALL

	  SELECT '18','SULAWESI TENGAH','1' FROM dual
 UNION ALL

	  SELECT '19','SULAWESI SELATAN','1' FROM dual
 UNION ALL

	  SELECT '20','SULAWESI TENGGARA','1' FROM dual
 UNION ALL

	  SELECT '21','MALUKU','1' FROM dual
 UNION ALL

	  SELECT '22','BALI','1' FROM dual
 UNION ALL

	  SELECT '23','NUSA TENGGARA BARAT','1' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '24','NUSA TENGGARA TIMUR','1' FROM dual
 UNION ALL

	  SELECT '25','PAPUA','1' FROM dual
 UNION ALL

	  SELECT '26','BENGKULU','1' FROM dual
 UNION ALL

	  SELECT '27','TIMOR-TIMUR','1' FROM dual
 UNION ALL

	  SELECT '99','LUAR NEGERI','1' FROM dual
 UNION ALL

	  SELECT '0101','JAKARTA SELATAN','2' FROM dual
 UNION ALL

	  SELECT '0102','JAKARTA TIMUR','2' FROM dual
 UNION ALL

	  SELECT '0103','JAKARTA PUSAT','2' FROM dual
 UNION ALL

	  SELECT '0104','JAKARTA BARAT','2' FROM dual
 UNION ALL

	  SELECT '0105','JAKARTA UTARA','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0201','KODYA BANDUNG','2' FROM dual
 UNION ALL

	  SELECT '0202','KODYA BOGOR','2' FROM dual
 UNION ALL

	  SELECT '0203','KODYA SUKABUMI','2' FROM dual
 UNION ALL

	  SELECT '0204','KODYA CIREBON','2' FROM dual
 UNION ALL

	  SELECT '0221','KOTIP TANGERANG','4' FROM dual
 UNION ALL

	  SELECT '0222','KOTIP TASIKMALAYA','4' FROM dual
 UNION ALL

	  SELECT '0223','KOTIP BEKASI','4' FROM dual
 UNION ALL

	  SELECT '0224','KOTIP DEPOK','4' FROM dual
 UNION ALL

	  SELECT '0225','KOTIP CIMAHI','4' FROM dual
 UNION ALL

	  SELECT '0231','KAB. PANDEGLANG','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0232','KAB. LEBAK','3' FROM dual
 UNION ALL

	  SELECT '0233','KAB. BOGOR','3' FROM dual
 UNION ALL

	  SELECT '0234','KAB. SUKABUMI','3' FROM dual
 UNION ALL

	  SELECT '0235','KAB. CIANJUR','3' FROM dual
 UNION ALL

	  SELECT '0236','KAB. BANDUNG','3' FROM dual
 UNION ALL

	  SELECT '0237','KAB. GARUT','3' FROM dual
 UNION ALL

	  SELECT '0238','KAB. TASIKMALAYA','3' FROM dual
 UNION ALL

	  SELECT '0239','KAB. CIAMIS','3' FROM dual
 UNION ALL

	  SELECT '0240','KAB. KUNINGAN','3' FROM dual
 UNION ALL

	  SELECT '0241','KAB. CIREBON','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0242','KAB. MAJALENGKA','3' FROM dual
 UNION ALL

	  SELECT '0243','KAB. SUMEDANG','3' FROM dual
 UNION ALL

	  SELECT '0244','KAB. INDRAMAYU','3' FROM dual
 UNION ALL

	  SELECT '0245','KAB. SUBANG','3' FROM dual
 UNION ALL

	  SELECT '0246','KAB. PURWAKARTA','3' FROM dual
 UNION ALL

	  SELECT '0247','KAB. KARAWANG','3' FROM dual
 UNION ALL

	  SELECT '0248','KAB. TANGERANG','3' FROM dual
 UNION ALL

	  SELECT '0249','KAB. SERANG','3' FROM dual
 UNION ALL

	  SELECT '0301','KODYA MAGELANG','2' FROM dual
 UNION ALL

	  SELECT '0302','KODYA SURAKARTA','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0303','KODYA SALATIGA','2' FROM dual
 UNION ALL

	  SELECT '0321','KOTIP PURWOKERTO','4' FROM dual
 UNION ALL

	  SELECT '0322','KOTIP CILACAP','4' FROM dual
 UNION ALL

	  SELECT '0331','KAB. CILACAP','3' FROM dual
 UNION ALL

	  SELECT '0332','KAB. BANYUMAS','3' FROM dual
 UNION ALL

	  SELECT '0333','KAB. PURBALINGGA','3' FROM dual
 UNION ALL

	  SELECT '0334','KAB. BANJARNEGARA','3' FROM dual
 UNION ALL

	  SELECT '0335','KAB. KEBUMEN','3' FROM dual
 UNION ALL

	  SELECT '0336','KAB. PURWOREJO','3' FROM dual
 UNION ALL

	  SELECT '0337','KAB. WONOSOBO','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0338','KAB. MAGELANG','3' FROM dual
 UNION ALL

	  SELECT '0339','KAB. BOYOLALI','3' FROM dual
 UNION ALL

	  SELECT '0340','KAB. KLATEN','3' FROM dual
 UNION ALL

	  SELECT '0341','KAB. SUKOHARJO','3' FROM dual
 UNION ALL

	  SELECT '0342','KAB. WONOGIRI','3' FROM dual
 UNION ALL

	  SELECT '0343','KAB. KARANG ANYAR','3' FROM dual
 UNION ALL

	  SELECT '0344','KAB. SRAGEN','3' FROM dual
 UNION ALL

	  SELECT '0345','KAB. GROBOGAN','3' FROM dual
 UNION ALL

	  SELECT '0346','KAB. BLORA','3' FROM dual
 UNION ALL

	  SELECT '0347','KAB. REMBANG','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0348','KAB. PATI','3' FROM dual
 UNION ALL

	  SELECT '0349','KAB. KUDUS','3' FROM dual
 UNION ALL

	  SELECT '0350','KAB. JEPARA','3' FROM dual
 UNION ALL

	  SELECT '0351','KAB. DEMAK','3' FROM dual
 UNION ALL

	  SELECT '0352','KAB. SEMARANG','3' FROM dual
 UNION ALL

	  SELECT '0353','KAB. TEMANGGUNG','3' FROM dual
 UNION ALL

	  SELECT '0354','KAB. KENDAL','3' FROM dual
 UNION ALL

	  SELECT '0355','KAB. BATANG','3' FROM dual
 UNION ALL

	  SELECT '0356','KAB. PEKALONGAN','3' FROM dual
 UNION ALL

	  SELECT '0357','KAB. PEMALANG','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0358','KAB. TEGAL','3' FROM dual
 UNION ALL

	  SELECT '0359','KAB. BREBES','3' FROM dual
 UNION ALL

	  SELECT '0401','KODYA YOGYAKARTA','2' FROM dual
 UNION ALL

	  SELECT '0431','KAB. KULON PROGO','3' FROM dual
 UNION ALL

	  SELECT '0432','KAB. BANTUL','3' FROM dual
 UNION ALL

	  SELECT '0433','KAB. GUNUNG KIDUL','3' FROM dual
 UNION ALL

	  SELECT '0434','KAB. SLEMAN','3' FROM dual
 UNION ALL

	  SELECT '0501','KODYA SURABAYA','2' FROM dual
 UNION ALL

	  SELECT '0502','KODYA MOJOKERTO','2' FROM dual
 UNION ALL

	  SELECT '0503','KODYA MALANG','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0504','KODYA PASURUAN','2' FROM dual
 UNION ALL

	  SELECT '0505','KODYA KEDIRI','2' FROM dual
 UNION ALL

	  SELECT '0506','KODYA BLITAR','2' FROM dual
 UNION ALL

	  SELECT '0507','KODYA PROBOLINGGO','2' FROM dual
 UNION ALL

	  SELECT '0508','KODYA MADIUN','2' FROM dual
 UNION ALL

	  SELECT '0521','KOTIP JEMBER','2' FROM dual
 UNION ALL

	  SELECT '0531','KAB. PACITAN','3' FROM dual
 UNION ALL

	  SELECT '0532','KAB. PONOROGO','3' FROM dual
 UNION ALL

	  SELECT '0533','KAB. TRENGGALEK','3' FROM dual
 UNION ALL

	  SELECT '0534','KAB. TULUNGAGUNG','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2253','AMLAMPURA',NULL FROM dual
 UNION ALL

	  SELECT '1236','METRO','4' FROM dual
 UNION ALL

	  SELECT '0535','KAB. BLITAR','3' FROM dual
 UNION ALL

	  SELECT '0536','KAB. KEDIRI','3' FROM dual
 UNION ALL

	  SELECT '0537','KAB. MALANG','3' FROM dual
 UNION ALL

	  SELECT '0538','KAB. LUMAJANG','3' FROM dual
 UNION ALL

	  SELECT '0539','KAB. JEMBER','3' FROM dual
 UNION ALL

	  SELECT '0540','KAB. BANYUWANGI','3' FROM dual
 UNION ALL

	  SELECT '0541','KAB. BONDOWOSO','3' FROM dual
 UNION ALL

	  SELECT '0542','KAB. PANARUKAN','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0543','KAB. PROBOLINGGO','3' FROM dual
 UNION ALL

	  SELECT '0544','KAB. PASURUAN','3' FROM dual
 UNION ALL

	  SELECT '0545','KAB. SIDOARJO','3' FROM dual
 UNION ALL

	  SELECT '0546','KAB. MOJOKERTO','3' FROM dual
 UNION ALL

	  SELECT '0547','KAB. JOMBANG','3' FROM dual
 UNION ALL

	  SELECT '0548','KAB. NGANJUK','3' FROM dual
 UNION ALL

	  SELECT '0549','KAB. MADIUN','3' FROM dual
 UNION ALL

	  SELECT '0550','KAB. MAGETAN','3' FROM dual
 UNION ALL

	  SELECT '0551','KAB. NGAWI','3' FROM dual
 UNION ALL

	  SELECT '0552','KAB. BOJONEGORO','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0553','KAB. TUBAN','3' FROM dual
 UNION ALL

	  SELECT '0554','KAB. LAMONGAN','3' FROM dual
 UNION ALL

	  SELECT '0555','KAB. GRESIK','3' FROM dual
 UNION ALL

	  SELECT '0556','KAB. BANGKALAN','3' FROM dual
 UNION ALL

	  SELECT '0557','KAB. SAMPANG','3' FROM dual
 UNION ALL

	  SELECT '0558','KAB. PAMEKASAN','3' FROM dual
 UNION ALL

	  SELECT '0559','KAB. SUMENEP','3' FROM dual
 UNION ALL

	  SELECT '0560','KAB. SITUBONDO','3' FROM dual
 UNION ALL

	  SELECT '0601','KODYA BANDA ACEH','2' FROM dual
 UNION ALL

	  SELECT '0602','KODYA SABANG','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0631','KAB. ACEH SELATAN','3' FROM dual
 UNION ALL

	  SELECT '0632','KAB. ACEH TENGGARA','3' FROM dual
 UNION ALL

	  SELECT '0633','KAB. ACEH TIMUR','3' FROM dual
 UNION ALL

	  SELECT '0634','KAB. ACEH TENGAH','3' FROM dual
 UNION ALL

	  SELECT '0635','KAB. ACEH BARAT','3' FROM dual
 UNION ALL

	  SELECT '0636','KAB. ACEH BESAR','3' FROM dual
 UNION ALL

	  SELECT '0637','KAB. ACEH UTARA','3' FROM dual
 UNION ALL

	  SELECT '0638','KAB. PIDIE','3' FROM dual
 UNION ALL

	  SELECT '0701','KODYA MEDAN','2' FROM dual
 UNION ALL

	  SELECT '0702','KODYA SIBOLGA','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0703','KODYA TANJUNG BALAI','2' FROM dual
 UNION ALL

	  SELECT '0704','KODYA PEMATANG SIANTAR','2' FROM dual
 UNION ALL

	  SELECT '0705','KODYA TEBING TINGGI','2' FROM dual
 UNION ALL

	  SELECT '0706','KODYA BINJAI','2' FROM dual
 UNION ALL

	  SELECT '0721','KOTIP KISARAN','4' FROM dual
 UNION ALL

	  SELECT '0731','KAB. NIAS','3' FROM dual
 UNION ALL

	  SELECT '0732','KAB. TAPANULI SELATAN','3' FROM dual
 UNION ALL

	  SELECT '0733','KAB. TAPANULI TENGAH','3' FROM dual
 UNION ALL

	  SELECT '0734','KAB. TAPANULI UTARA','3' FROM dual
 UNION ALL

	  SELECT '0735','KAB. LABUHAN RATU','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0736','KAB. ASAHAN','3' FROM dual
 UNION ALL

	  SELECT '0737','KAB. SIMALUNGUN','3' FROM dual
 UNION ALL

	  SELECT '0738','KAB. DAIRI','3' FROM dual
 UNION ALL

	  SELECT '0739','KAB. KARO','3' FROM dual
 UNION ALL

	  SELECT '0740','KAB. DELI SERDANG','3' FROM dual
 UNION ALL

	  SELECT '0741','KAB. LANGKAT','3' FROM dual
 UNION ALL

	  SELECT '0801','KODYA PADANG','2' FROM dual
 UNION ALL

	  SELECT '0802','KODYA SOLOK','2' FROM dual
 UNION ALL

	  SELECT '0803','KODYA SAWAHLUNTO','2' FROM dual
 UNION ALL

	  SELECT '0804','KODYA PADANG PANJANG','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0805','KODYA BUKIT TINGGI','2' FROM dual
 UNION ALL

	  SELECT '0806','KODYA PAYAKUMBUH','2' FROM dual
 UNION ALL

	  SELECT '0821','KOTIP PADANG SIDEMPUAN','4' FROM dual
 UNION ALL

	  SELECT '0831','KAB. PESISIR SELATAN','3' FROM dual
 UNION ALL

	  SELECT '0832','KAB. SOLOK','3' FROM dual
 UNION ALL

	  SELECT '0833','KAB. SAWAHLUNTO','3' FROM dual
 UNION ALL

	  SELECT '0834','KAB. TANAH DATAR','3' FROM dual
 UNION ALL

	  SELECT '0835','KAB. PADANG PARIAMAN','3' FROM dual
 UNION ALL

	  SELECT '0836','KAB. OGAN','3' FROM dual
 UNION ALL

	  SELECT '0837','KAB. LIMAPULUH KOTA','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0838','KAB. PASAMAN','3' FROM dual
 UNION ALL

	  SELECT '0901','KODYA PEKANBARU','2' FROM dual
 UNION ALL

	  SELECT '0921','KOTIP DUMAI','4' FROM dual
 UNION ALL

	  SELECT '0931','KAB. INDRAGIRI ULU','3' FROM dual
 UNION ALL

	  SELECT '0932','KAB. INDRAGIRI ILIR','3' FROM dual
 UNION ALL

	  SELECT '0933','KAB. KEPULAUAN RIAU','3' FROM dual
 UNION ALL

	  SELECT '0934','KAB. KAMPAR','3' FROM dual
 UNION ALL

	  SELECT '0935','KAB. BENGKALIS','3' FROM dual
 UNION ALL

	  SELECT '1001','KODYA JAMBI','2' FROM dual
 UNION ALL

	  SELECT '1031','KAB. JAMBI','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1032','KAB. MUARA BUNGO TEBO','3' FROM dual
 UNION ALL

	  SELECT '1033','KAB. TANJUNG JABUNG','3' FROM dual
 UNION ALL

	  SELECT '1034','KAB. BATANG HARI','3' FROM dual
 UNION ALL

	  SELECT '1035','KAB. BANGKO SARULANGUN','3' FROM dual
 UNION ALL

	  SELECT '1036','KAB. KERINCI','3' FROM dual
 UNION ALL

	  SELECT '1037','KAB. SAEKO','3' FROM dual
 UNION ALL

	  SELECT '1101','KODYA PALEMBANG','2' FROM dual
 UNION ALL

	  SELECT '1102','KODYA PANGKALPINANG','2' FROM dual
 UNION ALL

	  SELECT '1121','KOTIP LUBUK LINGGAU','4' FROM dual
 UNION ALL

	  SELECT '1122','KOTIP PRABUMULIH','4' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1131','KAB. OGAN KOMERING ULU','3' FROM dual
 UNION ALL

	  SELECT '1132','KAB. OGAN KOMERING ILIR','3' FROM dual
 UNION ALL

	  SELECT '1133','KAB. MUARA ENIM/LIOT','3' FROM dual
 UNION ALL

	  SELECT '1134','KAB. LAHAT','3' FROM dual
 UNION ALL

	  SELECT '1135','KAB. MUSI RAWAS','3' FROM dual
 UNION ALL

	  SELECT '1136','KAB. MUSI BANYUASIN','3' FROM dual
 UNION ALL

	  SELECT '1137','KAB. BANGKA','3' FROM dual
 UNION ALL

	  SELECT '1138','KAB. BELITUNG','3' FROM dual
 UNION ALL

	  SELECT '1201','KODYA TANJUNG KARANG','2' FROM dual
 UNION ALL

	  SELECT '1231','KAB. LAMPUNG SELATAN','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1232','KAB. LAMPUNG TENGAH','3' FROM dual
 UNION ALL

	  SELECT '1233','KAB. LAMPUNG UTARA','3' FROM dual
 UNION ALL

	  SELECT '1301','KODYA PONTIANAK','2' FROM dual
 UNION ALL

	  SELECT '1321','KOTIP SINGKAWANG','4' FROM dual
 UNION ALL

	  SELECT '1331','KAB. PONTIANAK','3' FROM dual
 UNION ALL

	  SELECT '1332','KAB. SAMBAS','3' FROM dual
 UNION ALL

	  SELECT '1333','KAB. SANGGAU','3' FROM dual
 UNION ALL

	  SELECT '1334','KAB. KETAPANG','3' FROM dual
 UNION ALL

	  SELECT '1335','KAB. SINTANG','3' FROM dual
 UNION ALL

	  SELECT '1336','KAB. KAPUAS HULU','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1401','KODYA PALANGKARAYA','2' FROM dual
 UNION ALL

	  SELECT '1431','KAB. KOTA WARINGIN BARAT','3' FROM dual
 UNION ALL

	  SELECT '1432','KAB. KOTA WARINGIN TIMUR','3' FROM dual
 UNION ALL

	  SELECT '1433','KAB. KATINGAN','3' FROM dual
 UNION ALL

	  SELECT '1434','KAB. KAPUAS','3' FROM dual
 UNION ALL

	  SELECT '1435','KAB. BARITO SELATAN','3' FROM dual
 UNION ALL

	  SELECT '1436','KAB. BARITO TIMUR','3' FROM dual
 UNION ALL

	  SELECT '1437','KAB. BARITO UTARA','3' FROM dual
 UNION ALL

	  SELECT '1438','KAB. GUNUNG MAS','3' FROM dual
 UNION ALL

	  SELECT '1439','KAB. MURUNG RAYA','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1440','KAB. SERUYAN','3' FROM dual
 UNION ALL

	  SELECT '1501','KODYA BANJARMASIN','2' FROM dual
 UNION ALL

	  SELECT '1521','KOTIP BANJARBARU','4' FROM dual
 UNION ALL

	  SELECT '1522','KOTIP TARAKAN','4' FROM dual
 UNION ALL

	  SELECT '1531','KAB. TANAH LAUT','3' FROM dual
 UNION ALL

	  SELECT '1532','KAB. KOTA BARU','3' FROM dual
 UNION ALL

	  SELECT '1533','KAB. BANJAR','3' FROM dual
 UNION ALL

	  SELECT '1534','KAB. BARITOKUALA','3' FROM dual
 UNION ALL

	  SELECT '1535','KAB. TAPIN','3' FROM dual
 UNION ALL

	  SELECT '1536','KAB. HULU SEI SELATAN','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1537','KAB. HULU SEI TENGAH','3' FROM dual
 UNION ALL

	  SELECT '1538','KAB. HULU SEI UTARA','3' FROM dual
 UNION ALL

	  SELECT '1539','KAB. TABALONG','3' FROM dual
 UNION ALL

	  SELECT '1601','KODYA SAMARINDA','2' FROM dual
 UNION ALL

	  SELECT '1602','KODYA BALIKPAPAN','2' FROM dual
 UNION ALL

	  SELECT '1631','KAB. BERAU','3' FROM dual
 UNION ALL

	  SELECT '1632','KAB. BULONGAN','3' FROM dual
 UNION ALL

	  SELECT '1633','KAB. KUTAI','3' FROM dual
 UNION ALL

	  SELECT '1634','KAB. PASIR','3' FROM dual
 UNION ALL

	  SELECT '1701','KODYA MANADO','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1702','KODYA GORONTALO','2' FROM dual
 UNION ALL

	  SELECT '1721','KOTIP BITUNG','4' FROM dual
 UNION ALL

	  SELECT '1731','KAB. BOLAANG MANGANDOW','3' FROM dual
 UNION ALL

	  SELECT '1732','KAB. MINAHASA','3' FROM dual
 UNION ALL

	  SELECT '1733','KAB. SANGIHE TALAUD','3' FROM dual
 UNION ALL

	  SELECT '1821','KOTIP PALU','4' FROM dual
 UNION ALL

	  SELECT '1822','KOTIP BAU BAU','4' FROM dual
 UNION ALL

	  SELECT '1831','KAB. BUAL TOLI TOLI','3' FROM dual
 UNION ALL

	  SELECT '1832','KAB. DONGGALA','3' FROM dual
 UNION ALL

	  SELECT '1833','KAB. LUWUK/BANGGAI','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1834','KAB. POSO','3' FROM dual
 UNION ALL

	  SELECT '1901','KODYA UJUNG PANDANG','2' FROM dual
 UNION ALL

	  SELECT '1902','KODYA PARE PARE','2' FROM dual
 UNION ALL

	  SELECT '1961','LUWU TIMUR',NULL FROM dual
 UNION ALL

	  SELECT '1962','LUWU UTARA',NULL FROM dual
 UNION ALL

	  SELECT '1963','LUWU SELATAN',NULL FROM dual
 UNION ALL

	  SELECT '6666','RIYADH (ARAB SAUDI)',NULL FROM dual
 UNION ALL

	  SELECT '2254','AMLAPURA',NULL FROM dual
 UNION ALL

	  SELECT '2255','KEDIRI',NULL FROM dual
 UNION ALL

	  SELECT '1547','KAB. TANAH BUMBU','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1445','KAB. PULANGPISAU','3' FROM dual
 UNION ALL

	  SELECT '0936','KAB. TEMBILAHAN','3' FROM dual
 UNION ALL

	  SELECT '1548','KAB. TANJUNG TABELONG','3' FROM dual
 UNION ALL

	  SELECT '1648','KUTAI TIMUR','3' FROM dual
 UNION ALL

	  SELECT '2142','KODYA TUAL','2' FROM dual
 UNION ALL

	  SELECT '2549','KAB. MIMIKA','3' FROM dual
 UNION ALL

	  SELECT '1237','LAMPUNG TIMUR','3' FROM dual
 UNION ALL

	  SELECT '2550','WAROPEN','3' FROM dual
 UNION ALL

	  SELECT '9402','MALAYSIA(*salah)',NULL FROM dual
 UNION ALL

	  SELECT '1140','KABUPATEN OKU SELATAN','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '9422','Qatar',NULL FROM dual
 UNION ALL

	  SELECT '2551','TELUK BINTUNI','3' FROM dual
 UNION ALL

	  SELECT '2143','KEPULAUAN ARU','3' FROM dual
 UNION ALL

	  SELECT '9424','FILIPINA','2' FROM dual
 UNION ALL

	  SELECT '9425','MANILA','3' FROM dual
 UNION ALL

	  SELECT '9501','CANADA','2' FROM dual
 UNION ALL

	  SELECT '9502','ONTARIO','3' FROM dual
 UNION ALL

	  SELECT '9503','TORONTO','3' FROM dual
 UNION ALL

	  SELECT '9504','KITCHENER','3' FROM dual
 UNION ALL

	  SELECT '9505','SAINT-HYACINTHE','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1402','PURUK CAHU','3' FROM dual
 UNION ALL

	  SELECT '1302','KAB. MEMPAWAH','3' FROM dual
 UNION ALL

	  SELECT '961','NEDERLAND','2' FROM dual
 UNION ALL

	  SELECT '962','DELFT','3' FROM dual
 UNION ALL

	  SELECT '0839','TAMAN MAKMUR','3' FROM dual
 UNION ALL

	  SELECT '0840','TAMAN MAKMUR SILAUT II','3' FROM dual
 UNION ALL

	  SELECT '2540','NABIRE','3' FROM dual
 UNION ALL

	  SELECT '1039','TALANG BUKIT','3' FROM dual
 UNION ALL

	  SELECT '3311','MERAL KARIMUN','3' FROM dual
 UNION ALL

	  SELECT '0937','siak','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0639','KAB. LHOKSEUMAWE','3' FROM dual
 UNION ALL

	  SELECT '0595','SIDOARJO','3' FROM dual
 UNION ALL

	  SELECT '0270','DEPOK','2' FROM dual
 UNION ALL

	  SELECT '0271','BEKASI','3' FROM dual
 UNION ALL

	  SELECT '35','KALIMANTAN UTARA','1' FROM dual
 UNION ALL

	  SELECT '351','KAB BULUNGAN','2' FROM dual
 UNION ALL

	  SELECT '0106','JAKARTA','4' FROM dual
 UNION ALL

	  SELECT '2462','BOBOU','3' FROM dual
 UNION ALL

	  SELECT '2256','TEMUKUS','3' FROM dual
 UNION ALL

	  SELECT '1446','KUALA KAPUAS','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2239','NAGARA','3' FROM dual
 UNION ALL

	  SELECT '2463','KAB. MANGGARAI TIMUR','3' FROM dual
 UNION ALL

	  SELECT '2552','BADE','3' FROM dual
 UNION ALL

	  SELECT '2553','MAPPI','3' FROM dual
 UNION ALL

	  SELECT '0751','TOBA SAMOSIR','3' FROM dual
 UNION ALL

	  SELECT '1238','TANJUNG RATU','3' FROM dual
 UNION ALL

	  SELECT '2554','MIMIKA','3' FROM dual
 UNION ALL

	  SELECT '1823','LAPOLA','4' FROM dual
 UNION ALL

	  SELECT '2555','TIMIKA','3' FROM dual
 UNION ALL

	  SELECT '1740','TOMOHOM','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1741','TOMOHON','3' FROM dual
 UNION ALL

	  SELECT '1239','PURWODADI','3' FROM dual
 UNION ALL

	  SELECT '1549','HULU SUNGAN SELATAN','3' FROM dual
 UNION ALL

	  SELECT '1550','KANDANGAN','2' FROM dual
 UNION ALL

	  SELECT '2556','YAHUKIMO','3' FROM dual
 UNION ALL

	  SELECT '2557','WAENA','4' FROM dual
 UNION ALL

	  SELECT '0272','BANJAR','2' FROM dual
 UNION ALL

	  SELECT '2558','NETAHUA','4' FROM dual
 UNION ALL

	  SELECT '2559','SENTANI','3' FROM dual
 UNION ALL

	  SELECT '1742','KOLONGAN','4' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2560','HALUWON','4' FROM dual
 UNION ALL

	  SELECT '2561','KORUPUN','4' FROM dual
 UNION ALL

	  SELECT '1338','KAPUAS HULU','3' FROM dual
 UNION ALL

	  SELECT '2562','ABEPURA','3' FROM dual
 UNION ALL

	  SELECT '1040','PERENTAK','3' FROM dual
 UNION ALL

	  SELECT '1965','SIDENRENG RAPPANG','3' FROM dual
 UNION ALL

	  SELECT '1551','SUNGAI PINANG','3' FROM dual
 UNION ALL

	  SELECT '0938','TEMBILAHAN','3' FROM dual
 UNION ALL

	  SELECT '1339','SEMITAU','3' FROM dual
 UNION ALL

	  SELECT '2337','SAKRA','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '1447','KUMAI','3' FROM dual
 UNION ALL

	  SELECT '0596','SURABAYA','2' FROM dual
 UNION ALL

	  SELECT '0597','BOJONEGORO','2' FROM dual
 UNION ALL

	  SELECT '2257','DENPASAR','2' FROM dual
 UNION ALL

	  SELECT '0598','BANYUWANGI','3' FROM dual
 UNION ALL

	  SELECT '0362','KLATEN','3' FROM dual
 UNION ALL

	  SELECT '9426','DILI','2' FROM dual
 UNION ALL

	  SELECT '0599','MOJOKERTO','4' FROM dual
 UNION ALL

	  SELECT '0510','BLITAR','2' FROM dual
 UNION ALL

	  SELECT '0511','JOMBANG','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0363','SALATIGA','2' FROM dual
 UNION ALL

	  SELECT '0512','SUMENEP','2' FROM dual
 UNION ALL

	  SELECT '0513','KABUPATEN TUBAN','2' FROM dual
 UNION ALL

	  SELECT '1141','PALEMBANG','2' FROM dual
 UNION ALL

	  SELECT '0514','TUBAN','2' FROM dual
 UNION ALL

	  SELECT '0515','SAMPANG','3' FROM dual
 UNION ALL

	  SELECT '0516','TRENGGALEK','2' FROM dual
 UNION ALL

	  SELECT '0517','MAGETAN','2' FROM dual
 UNION ALL

	  SELECT '0518','GRESIK','2' FROM dual
 UNION ALL

	  SELECT '0446','BANTUL','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2144','AMBON','2' FROM dual
 UNION ALL

	  SELECT '0364','SUKOHARJO','3' FROM dual
 UNION ALL

	  SELECT '0561','LAMONGAN','2' FROM dual
 UNION ALL

	  SELECT '1650','SAMARINDA','2' FROM dual
 UNION ALL

	  SELECT '0562','LUMAJANG','2' FROM dual
 UNION ALL

	  SELECT '0563','PASURUAN','2' FROM dual
 UNION ALL

	  SELECT '0564','TULUNGAGUNG','2' FROM dual
 UNION ALL

	  SELECT '0752','MEDAN','2' FROM dual
 UNION ALL

	  SELECT '0565','NGANJUK','2' FROM dual
 UNION ALL

	  SELECT '1743','MANADO','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2338','MATARAM','2' FROM dual
 UNION ALL

	  SELECT '0566','BANGKALAN','2' FROM dual
 UNION ALL

	  SELECT '2339','LAB. LALAR','4' FROM dual
 UNION ALL

	  SELECT '1840','PALU','2' FROM dual
 UNION ALL

	  SELECT '1240','TANGGUL ANGIN','4' FROM dual
 UNION ALL

	  SELECT '0509','MADIUN','2' FROM dual
 UNION ALL

	  SELECT '1651','BERAU','3' FROM dual
 UNION ALL

	  SELECT '0567','NGAWI','2' FROM dual
 UNION ALL

	  SELECT '0568','PONOROGO','2' FROM dual
 UNION ALL

	  SELECT '0569','PROBOLINGGO','2' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '2853','SERANG','2' FROM dual
 UNION ALL

	  SELECT '0570','JEMBER','2' FROM dual
 UNION ALL

	  SELECT '0273','BOGOR','2' FROM dual
 UNION ALL

	  SELECT '1603','BALIKPAPAN','1' FROM dual
 UNION ALL

	  SELECT '0571','PAMEKASAN','2' FROM dual
 UNION ALL

	  SELECT '3512','KABUPATEN BULUNGAN','2' FROM dual
 UNION ALL

	  SELECT '0370','REMBANG','2' FROM dual
 UNION ALL

	  SELECT '0372','CILACAP','3' FROM dual
 UNION ALL

	  SELECT '0841','UJUNG GADING','3' FROM dual
 UNION ALL

	  SELECT '1340','KETAPANG','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0373','BLORA','3' FROM dual
 UNION ALL

	  SELECT '0374','PATI','3' FROM dual
 UNION ALL

	  SELECT '0375','KUDUS','3' FROM dual
 UNION ALL

	  SELECT '2466','ENDE','4' FROM dual
 UNION ALL

	  SELECT '1553','BANJARMASIN','4' FROM dual
 UNION ALL

	  SELECT '1968','TEMBAN','4' FROM dual
 UNION ALL

	  SELECT '2343','SUMBAWA','4' FROM dual
 UNION ALL

	  SELECT '0376','BREBES','3' FROM dual
 UNION ALL

	  SELECT '0377','KARANGANYAR','3' FROM dual
 UNION ALL

	  SELECT '0275','INDRAMAYU','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0276','KARAWANG','3' FROM dual
 UNION ALL

	  SELECT '0378','CEPU','2' FROM dual
 UNION ALL

	  SELECT '0277','SUKABUMI','2' FROM dual
 UNION ALL

	  SELECT '1341','SANDAI','4' FROM dual
 UNION ALL

	  SELECT '0379','SOLO','2' FROM dual
 UNION ALL

	  SELECT '2566','JAYAPURA','2' FROM dual
 UNION ALL

	  SELECT '0573','BONDOWOSO','2' FROM dual
 UNION ALL

	  SELECT '2346','LANTUNG SEPUKUR','3' FROM dual
 UNION ALL

	  SELECT '0205','BANDUNG','2' FROM dual
 UNION ALL

	  SELECT '2258','BULELENG','3' FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO KOTA_MF (ID,NAMA,JENIS)
	  SELECT '0381','TEMANGGUNG','2' FROM dual
 UNION ALL

	  SELECT '1653','PASER','4' FROM dual
 UNION ALL

	  SELECT '2567','MANOKWARI','4' FROM dual
 UNION ALL

	  SELECT '2039','TAKIMPO','3' FROM dual
 UNION ALL

	  SELECT '1142','KERTA MUKTI','3' FROM dual
 UNION ALL

	  SELECT '0278','CIREBON','3' FROM dual
 UNION ALL

	  SELECT '0591','SITUBONDO','2' FROM dual
 UNION ALL

	  SELECT '9506','BOLIVAR','2' FROM dual
 UNION ALL

	  SELECT '0519','KOTA MADIUN','2' FROM dual
 UNION ALL

	  SELECT '2467','NAGEKEO','3' FROM dual;
