-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9044,'KONSTRUKSI KAPAL BAJA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9043,'ELEKTRONIKA PESAWAT UDARA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9026,'KONTROL MEKANIK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9045,'TEKNIK LAS KAPAL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9046,'INSTALASI PERMESINAN KAPAL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9048,'GAMBAR RANCANG BANGUN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9013,'TEKNIK ELEKTRONIKA KOMUNIKASI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9003,'BAHASA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9015,'TEKNIK AUDIO-VIDEO',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9016,'TEKNIK INSTALASI LISTRIK',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9017,'TEKNIK LISTRIK JARINGAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 20,'MULTIMEDIA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9021,'TEKNIK INFORMATIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9022,'SALURAN KOMUNIKASI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9023,'SUITSING',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9024,'JARINGAN KABEL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9025,'KONTROL PROSES',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9027,'INSTRUMENTASI LOGAM DAN GELAS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9028,'TEKNIK LAS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9029,'TEKNIK PEMBENTUKAN',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9030,'TEKNIK TEMPA DAN COR',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9031,'TEKNIK MESIN PERKAKAS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9032,'TEKNIK MEKANIK INDUSTRI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9033,'TEKNIK GAMBAR MESIN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9009,'TEKNIK GAMBAR BANGUNAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9034,'TEKNIK MEKANIK OTOMOTIF',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9047,'LISTRIK KAPAL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9036,'TEKNIK BODI OTOMOTIF',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9010,'TEKNIK SURVAI DAN PEMETAAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9037,'PEMESINAN',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9038,'TEKNIK KOMPUTER JARINGAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9039,'KONSTRUKSI BADAN PESAWAT UDARA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9011,'TEKNIK PLAMBING DAN SANITASI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9040,'AIRFRAME & POWERPLANT MR',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9041,'AEI MAINTENANCE & REPAIR',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9042,'KELISTRIKAN PESAWAT UDARA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9014,'TEKNIK ELEKTRONIKA INDUSTRI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9019,'TEKNIK LISTRIK INDUSTRI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9035,'TEKNIK ALAT BERAT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9049,'BANGUNAN KAPAL NON BAJA',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9050,'INTERIOR KAPAL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9051,'TEKNIK PERIKANAN LAUT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9052,'REKAYA PERANGKAT LUNAK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9053,'PERSIAPAN GRAFIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9054,'PRODUKSI GRAFIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9055,'TEKNIK PEMINTALAN SERAT BUATAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9056,'TEKNIK PEMBUATAN BENANG',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9057,'TEKNIK PEMBUATAN KAIN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9058,'TEKNIK PENYEMPURNAAN TEKSTIL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9059,'TEKNIK PRODUKSI PAKAIAN JADI',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9060,'GEOLOGI PERTAMBANGAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9062,'ANALISIS KIMIA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9063,'TEKNIKA KAPAL NIAGA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9064,'TEKNIKA KAPAL PERIKANAN LAUT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9067,'BUDIDAYA TANAMAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9068,'BUDIDAYA IKAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9069,'BUDIDAYA TERNAK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9070,'MEKANISASI PERTANIAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9066,'NAUTIKA PERIKANAN LAUT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9071,'TEKNOLOGI HASIL PERTANIAN',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9074,'PERBANKAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9075,'PENJUALAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9076,'ASURANSI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9077,'KOPERASI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9079,'AKOMODASI PERHOTELAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9080,'TATA BOGA (RESTORAN)',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9081,'TATA BUSANA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9082,'TATA KECANTIKAN RAMBUT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9083,'TATA KECANTIKAN KULIT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9084,'PEKERJAAN SOSIAL',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9085,'SENI RUPA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9086,'KRIA KAYU',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9087,'KRIA LOGAM',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9088,'KRIA TEKSTIL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9089,'KRIA KERAMIK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9090,'KRIA KULIT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9091,'SENI MUSIK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9092,'SENI KARAWITAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9093,'SENI TARI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9094,'SENI TEATER',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9095,'BANGUNAN GEDUNG',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9096,'BANGUNAN AIR',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9097,'PERABOT KAYU',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9098,'TEKNIKA PENANGKAPAN IKAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9099,'TEKNIK TELEFONI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9100,'TEKNIK TRANSMISI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9101,'LISTRIK TENAGA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9102,'MESIN PRODUKSI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9103,'MESIN KONSTRUKSI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9104,'MEKANIK UMUM',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9105,NULL,NULL,NULL FROM dual
 UNION ALL

	  SELECT 9106,'PELAYARAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9107,'GAMBAR RANCANG BANGUN KAPAL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9108,'TEKNOLOGI PEMINTALAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9109,'TEKNOLOGI PERTENUNAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9110,'TEKNOLOGI PERAJUTAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9111,'TEKNIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9112,'NAUTIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9113,'TEKNOLOGI PENANGKAPAN IKAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9114,'USAHATANI TERPADU',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9115,'MANAJEMEN BISNIS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9116,'PATISERI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9117,'GIZI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9118,'PELAYANAN SOSIAL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9119,'PENGEMBANGAN MASYARAKAT',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9120,'KERAJINAN KAYU',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9121,'KERAJINAN LOGAM',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9122,'KERAJINAN TEKSTIL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9123,'KERAJINAN KERAMIK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9124,'KERAJINAN KULIT',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 9125,'PROGRAM KEAGAMAAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9126,'KESEHATAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 9012,'TEKNIK PERKAYUAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 48,'TEKNIK KOMPUTER DAN INFORMATIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 52,'HJGNGHJGHJ',NULL,NULL FROM dual
 UNION ALL

	  SELECT 51,'TEKNIK MESIN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 59,'NAUTIKA KAPAL NIAGA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 60,'TEKNIK OTOMOTIF KENDARAAN RINGAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 71,'BROADCASTING',NULL,NULL FROM dual
 UNION ALL

	  SELECT 73,'GAMBAR RANCANG BANGUN KAPAL',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 76,'AGRIBISNIS PRODUKSI TERNAK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 38,'TEKNIK KOMPUTER JARINGAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 58,'TEKNIK PEMANFAATAN TENAGA LISTRIK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 70,'AGAMA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 66,'TEKNIK INFORMASI DAN KOMPUTER',NULL,NULL FROM dual
 UNION ALL

	  SELECT 62,'SLB-B',NULL,NULL FROM dual
 UNION ALL

	  SELECT 11,'SMA A1',NULL,NULL FROM dual
 UNION ALL

	  SELECT 12,'SMA A2',NULL,NULL FROM dual
 UNION ALL

	  SELECT 13,'SMA A3',NULL,NULL FROM dual
 UNION ALL

	  SELECT 15,'SMU IPA',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 16,'SMU IPS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 21,'STM LISTRIK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 22,'STM ELEKTRONIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 23,'STM MESIN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 24,'STM SIPIL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 25,'SMK MESIN TENAGA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 26,'SMK LISTRIK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 27,'SMK ELEKTRO',NULL,NULL FROM dual
 UNION ALL

	  SELECT 28,'SMK BANGUNAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 29,'SMK OTOMOTIF',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 31,'MANAJEMEN BISNIS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 32,'AKUNTANSI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 33,'PERKANTORAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 34,'KOPERASI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 35,'SEKRETARIS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 40,'FARMASI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 41,'KESEJAHTERAAN KELUARGA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 42,'PARIWISATA PERHOTELAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 43,'LAIN-LAIN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 14,'SMA A4',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 30,'SMK INFORMATIKA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 45,'SMK TEKNOLOGI DAN INDUSTRI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 46,'SMK KIMIA INDUSTRI',NULL,NULL FROM dual
 UNION ALL

	  SELECT 54,'TEKNOLOGI PESAWAT UDARA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 47,'MESIN OTOMOTIF',NULL,NULL FROM dual
 UNION ALL

	  SELECT 49,'TEKNIK PRODUKSI MIGAS',NULL,NULL FROM dual
 UNION ALL

	  SELECT 55,'SMK TATA BUSANA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 56,'TAT BUSANA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 61,'DESAIN KOMUNIKASI VISUAL',NULL,NULL FROM dual
 UNION ALL

	  SELECT 63,'ANIMASI',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 64,'ADMINISTRASI PERKANTORAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 65,'TEKNIK PERKAPALAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 67,'TEKNIK BANGUNAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 72,'USAHA PERJALANAN WISATA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 75,'TEKNIK SEPEDA MOTOR',NULL,NULL FROM dual
 UNION ALL

	  SELECT 77,'TEKNIK KONSTRUKSI KAYU',NULL,NULL FROM dual
 UNION ALL

	  SELECT 78,'TATA BUSANA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 81,'DESAIN INTERIOR',NULL,NULL FROM dual
 UNION ALL

	  SELECT 17,'SMU BAHASA',NULL,NULL FROM dual
 UNION ALL

	  SELECT 50,'MUSIK KLASIK',NULL,NULL FROM dual;
-- SQLINES LICENSE FOR EVALUATION USE ONLY
INSERT INTO JURUSAN_SMU (KD_JURUSAN,NAMA,KET,KEL)
	  SELECT 57,'ELECTRICAL AVIONIC',NULL,NULL FROM dual
 UNION ALL

	  SELECT 53,'REKAYASA PERANGKAT LUNAK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 68,'PEMASARAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 69,'KEPERAWATAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 74,' KESEHATAN',NULL,NULL FROM dual
 UNION ALL

	  SELECT 79,'MEK',NULL,NULL FROM dual
 UNION ALL

	  SELECT 80,'TEKNIK MEKATRONIKA',NULL,NULL FROM dual;
